name: Dependency Graph
on:
  push:
    branches:
      - main

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  dependency-graph:
    name: Submit dependencies to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: sbt/setup-sbt@v1
      - uses: mkurz/sbt-dependency-submission@manifest-prefix
        with:
          correlator: '${{ github.workflow }}_${{ github.job }}_${{ github.action }}_${{ github.ref_name }}'
          # By hardcoding the sha and ref, we ensure that all branches update the same snapshots, differing only by their correlator.
          sha-override: '2928f9df288a990680872bb05a170b4174ff9557'
          ref-override: 'refs/heads/main' #  2025-02-27: GitHub ignores it, but to be future-proof, let's hardcode it (not using github.event.repository.default_branch)
          sbt-plugin-version: '3.2.0-SNAPSHOT'
